_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.9.13
        t:
            "1":
                - 2
                - 3
                - 55
            "2":
                - 2
                - 3
                - 55
            "3":
                - 3
                - 8
                - 13
                - 16
                - 23
                - 55
                - 62
            "4": 3.9.13
            "5": 0.19.1
            "8":
                - 3
                - 5
            "10":
                - 17
            "12": 0.19.1
            "13": windows-amd64
batch_size:
    value: 200
digits:
    value:
        - 0
        - 4
epochs:
    value: 10
optimizer:
    value: rmsprop
